export const SET_PRODUCT_NUMBER = 'SET_PRODUCT_NUMBER';
export const PRODUCT_NUMBER_VALIDATION_ERROR = 'PRODUCT_NUMBER_VALIDATION_ERROR';
export const SET_AMOUNT = 'SET_AMOUNT';
export const SET_TOTAL_COST = 'SET_TOTAL_COST';